import './globals.css'
import { inter } from '@/utils/fonts'
import Navbar from '@/components/navbar/Navbar'
import Footer from '@/components/footer/Footer'
import { ScrollProvider } from '@/context/ScrollContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container'>
          <ScrollProvider>
            <Navbar />
            {children}
            <Footer />
          </ScrollProvider>
        </div>
      </body>
    </html>
  )
}
