// import { Inter } from 'next/font/google'
import './globals.css'
import { inter } from '@/utils/fonts'
import App from './App'

// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='container'>
          <App children={children} />
        </div>
      </body>
    </html>
  )
}
